name: my-first-workflow

on: [push]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "welcome to my first github workflow"
            
            - name: list files
              run: ls 

            - name: read file
              run: cat README.md
              
