name: Exploring variables and secrets

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '*/1 * * * *'
  # push

# environment variables can be defined at the workflow level, job level, or step level
# environment variables defined at the workflow level are available to all jobs and steps in the workflow
# environment variables defined at the job level are available to all steps in the job
# environment variables defined at the step level are available to the step in which they are defined and child steps

## environmental variables at workflow level

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
    IMAGE_TAG: latest
    

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

            - name: docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
   
            - name: docker publish
              run: echo docker push $CONTAINER_REGISTRy/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: |
               echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
               sleep 600s

